### ISSUE TITLE
Add retry for Pulp requests

### ISSUE THREAD

**Issue by emilyzheng** [release-engineering/ubi-population-tool#32]
Requests to Pulp sometimes get connection error:
```
2019-03-28 04:42:45 +0000 [INFO    ] Publishing ubi-7-server-source-rpms__7_DOT_3__x86_64 in yum_distributor
Traceback (most recent call last):
  File "/home/tester/venv/bin/ubipop", line 11, in <module>
    load_entry_point('ubi-population-tool==0.1.4', 'console_scripts', 'ubipop')()
  File "build/bdist.linux-x86_64/egg/ubipop/cli.py", line 64, in entry_point
  File "build/bdist.linux-x86_64/egg/ubipop/cli.py", line 59, in main
  File "build/bdist.linux-x86_64/egg/ubipop/__init__.py", line 91, in populate_ubi_repos
  File "build/bdist.linux-x86_64/egg/ubipop/__init__.py", line 361, in run_ubi_population
  File "build/bdist.linux-x86_64/egg/ubipop/_pulp_client.py", line 110, in wait_for_tasks
  File "build/bdist.linux-x86_64/egg/ubipop/_pulp_client.py", line 123, in search_tasks
  File "build/bdist.linux-x86_64/egg/ubipop/_pulp_client.py", line 42, in do_request
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
It would be better if requests can be retried than interrupting the population process immediately once there's any connection error.

**Comment by alexandrevicenzi** [comment]
Sometimes when running ubi-pop I get:

`ConnectionError: ('Connection aborted.', BadStatusLine("''",))`

This is an error that it's difficult to reproduce, and it happens due to network errors (especially on wifi or VPN), and my question is:

**Should ubi-pop try to deal with this or just explode as it's happening.**

As a tool that should publish things somewhere, I get bothered when it explodes with any useful message. Ok, the connection was aborted, just try again, I don't care if it was aborted, it's not my responsibility to deal with this, ubi-pop should be responsible for it.

Populating repos is slow, the matrix can be huge (based on multiple packages to multiple repos in multiple arches), and sometimes it fails in the middle/almost end of the process and I need to restart from scratch.

We need to keep in mind that this tool will be used continuously and it should try to avoid breaking the execution flow for such things, it should only stop the execution if something really bad happens, like, no network anymore, API changed, or similar.

@rbikar, @rohanpm what are your thoughts on this?

**Comment by rohanpm** [comment]
I believe it should deal with it.  Across all of our tools, I suggest the strategy should be to allow some retries for any idempotent operation involving a remote system.

I think of it like this:

- When a user asks a tool "do X", we can interpret that either as "attempt once to do X" or "do whatever it takes to accomplish X".  I'm sure the latter is what our users really want in most scenarios.
- There's a whole chain of systems outside of our control which need to be working in order for this tool to work.  Pulp, load balancing appliance in front of Pulp, the DB server behind Pulp, the filesystems behind all these and the networks connecting them.  These will always be subject to outages, both scheduled and unscheduled.  Rather than pretending like those systems are always working or that root causes of outages can always be addressed, it makes sense to design some tolerance for outages directly into the tools, which to me means retrying anything idempotent.

**Comment by rbikar** [comment]
Well I thought, if we use:
```python
  self._executor = Executors.thread_pool(max_workers=workers_count).with_retry()
```
then when pulp request fails, RetryExecutor will retry that request. Or what I miss there?

**Comment by rohanpm** [comment]
@rbikar yeah, that should be working.  But in the stack trace originally given, the failure is coming from calls to self.pulp.wait_for_tasks in run_ubi_population and those requests are not going through the executor.

So, only a portion of the requests to Pulp are currently covered by retries.
